### ISSUE TITLE
IIS Hosting

### ISSUE THREAD

**Issue by IanCarson10** [InsolvencyService/RPSCalculationEngine#10]
Is there any guidance on hosting the engine in IIS?

**Comment by atifmir** [comment]
@IanCarson10 hosting option is purely your/organisation's choice we are unable to advise, however, this link will help if you want to host dotnet core API in iis or explore other hosting options
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2

**Comment by IanCarson10** [comment]
Thanks.  I managed to get this working.
